<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>ExampleGame</AssemblyName>
    <RootNamespace>ExampleGame</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\OrbedenCore\Managed\Orbeden.Runtime\Orbeden.Runtime.csproj" PrivateAssets="all" Private="false" />
  </ItemGroup>

  <Target Name="RemoveRuntimeCopy" AfterTargets="Build">
    <Delete Files="$(OutputPath)Orbeden.Runtime.dll;$(OutputPath)Orbeden.Runtime.pdb;$(OutputPath)Orbeden.Runtime.deps.json" />
  </Target>
</Project>
