using System.Text;

namespace OrbedenDocGen;

/// <summary>把页面模型渲染成 Markdown 并落盘，同时清掉上一轮留下、本轮不再产出的页。</summary>
/// <remarks>
/// 输出必须逐字节稳定：不写时间戳、不写绝对路径、不写机器相关信息，排序全部用序数比较。
/// 每个文件首行是固定标记，清理只认这一行，人手写进同一目录的文件不受影响。
/// </remarks>
internal sealed class MarkdownWriter(string outputDirectory)
{
    /// <summary>生成物标记，必须是每个文件的第一行。</summary>
    internal const string Marker = "<!-- generated by OrbedenDocGen; do not edit -->";

    private readonly string root = outputDirectory;
    private readonly HashSet<string> written = new(StringComparer.OrdinalIgnoreCase);

    /// <summary>本轮写出的文件相对路径，供统计与自检使用。</summary>
    internal IReadOnlyCollection<string> Written => written;

    /// <summary>写一个页面；内容没变就不碰磁盘，越出输出目录的路径直接拒绝。</summary>
    internal void Write(string relativePath, string text)
    {
        var relative = relativePath.Replace('\\', '/');
        var path = Path.GetFullPath(Path.Combine(root, relative.Replace('/', Path.DirectorySeparatorChar)));
        var escape = Path.GetRelativePath(root, path);
        if (escape == ".." || escape.StartsWith(".." + Path.DirectorySeparatorChar, StringComparison.Ordinal) || Path.IsPathRooted(escape))
            throw new IOException($"Refusing to write outside the output directory: {relative}");
        written.Add(relative);
        WriteChanged(path, text);
    }

    /// <summary>删除本目录下带生成标记、但本轮没产出的 Markdown 文件。</summary>
    internal List<string> Prune()
    {
        List<string> removed = [];
        foreach (var path in Directory.EnumerateFiles(root, "*.md", SearchOption.AllDirectories).OrderBy(value => value, StringComparer.Ordinal))
        {
            var relative = Path.GetRelativePath(root, path).Replace('\\', '/');
            if (written.Contains(relative)) continue;
            if (FirstLine(path) != Marker) continue;
            File.Delete(path);
            removed.Add(relative);
        }
        return removed;
    }

    //逐行比较后写入，第二次运行是空操作
    private static void WriteChanged(string path, string text)
    {
        if (File.Exists(path) && File.ReadAllText(path) == text) return;
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, text, new UTF8Encoding(false));
    }

    private static string FirstLine(string path)
    {
        using var reader = new StreamReader(path, Encoding.UTF8);
        return reader.ReadLine() ?? "";
    }

    /// <summary>渲染类型页。</summary>
    internal static string RenderPage(DocPage page, IReadOnlyDictionary<string, string> pagesByTypeName)
    {
        StringBuilder output = new();
        output.Append(Marker).Append('\n').Append('\n');
        output.Append("# ").Append(page.Name).Append("\n\n");
        output.Append('`').Append(page.Kind).Append("`　·　命名空间 `").Append(page.Namespace).Append("`\n\n");
        output.Append("```csharp\n").Append(page.Declaration).Append("\n```\n\n");
        if (page.Summary.Length != 0) output.Append(Escape(page.Summary)).Append("\n\n");

        if (page.BaseTypeName != null)
        {
            var name = ShortName(page.BaseTypeName);
            if (pagesByTypeName.TryGetValue(page.BaseTypeName, out var target))
                output.Append("基类型：[").Append(name).Append("](").Append(RelativeLink(page.Category, target)).Append(")\n\n");
            else if (!page.BaseTypeName.StartsWith("System.", StringComparison.Ordinal))
                output.Append("基类型：").Append(name).Append("\n\n");
        }

        string? section = null;
        foreach (var entry in page.Entries)
        {
            if (entry.Section != section)
            {
                section = entry.Section;
                output.Append("## ").Append(section).Append("\n\n");
                if (section == "枚举值") output.Append("| 名称 | 值 | 说明 |\n| --- | --- | --- |\n");
            }

            //枚举成员只占表格一行，几十个常量不该摊成几十段标题
            if (section == "枚举值")
            {
                output.Append("| <a id=\"").Append(entry.Anchor).Append("\"></a>`").Append(entry.Title).Append("` | `").Append(entry.Signature).Append("` | ").Append(Cell(entry.Summary)).Append(" |\n");
                continue;
            }

            output.Append("<a id=\"").Append(entry.Anchor).Append("\"></a>\n");
            output.Append("### ").Append(entry.Title).Append("\n\n");
            if (entry.Signature.Length != 0) output.Append("```csharp\n").Append(entry.Signature).Append("\n```\n\n");
            if (entry.Summary.Length != 0) output.Append(Escape(entry.Summary)).Append("\n\n");
            if (entry.Serialized || entry.Changed.Length != 0) output.Append("**编辑器**：").Append(EditorFlags(entry)).Append("\n\n");
            if (entry.Cpp.Length != 0) output.Append("> C++：`").Append(entry.Cpp).Append("`\n\n");
        }

        if (page.Entries.Count == 0) output.Append("本类型没有公开成员。\n\n");
        //表格后必须空一行，否则分隔线和最后一行会被当成同一张表
        else if (section == "枚举值") output.Append('\n');
        output.Append("---\n\n");
        output.Append("[返回索引](../index.md)\n");
        return output.ToString();
    }

    /// <summary>渲染索引页。</summary>
    internal static string RenderIndex(List<DocPage> pages, DocDocument projection, ManifestCounts counts)
    {
        StringBuilder output = new();
        output.Append(Marker).Append("\n\n");
        output.Append("# Orbeden API 参考\n\n");
        output.Append("C# 脚本侧的 API 参考，从绑定投影、托管程序集反射与编译器产出的注释三份输入生成。\n\n");

        output.Append("## 覆盖范围\n\n");
        output.Append("本参考收录游戏脚本能直接用到的类型：\n\n");
        output.Append("- **组件与引擎对象**：`Orbeden.Object` 派生的对象、组件与资源包装，即绑定生成器产出 `[NativeBinding]` 的那些类型。\n");
        output.Append("- **值类型与枚举**：C++ 侧的值结构与枚举在托管侧的对应类型。\n");
        output.Append("- **托管层**：手写的托管类型，例如 `Ens`、`World`、`Resources`、`GUI` 与 `vector3` 这类值类型。\n\n");
        output.Append("不在范围内：引擎内部的 C++ 类型、没有导出到托管侧的成员，以及 Orbeden 命名空间之外的类型。\n\n");
        output.Append("每个页面的成员只列**该类型自己声明**的公开成员；从基类继承来的成员请到基类型页看。\n\n");

        output.Append("## 锚点规则\n\n");
        output.Append("页面路径就是类型锚点，例如 `components/Transform.md`。成员锚点由成员标识算出，与渲染出的标题无关：\n\n");
        output.Append("- 单个成员：`<a id=\"m-<成员名小写>\"></a>`，例如 `m-static`。\n");
        output.Append("- 重载方法：追加该档的参数个数，例如 `m-getmanagedcomponent-1`、`m-getmanagedcomponent-2`。\n");
        output.Append("- 构造函数：`m-ctor`，重载时同样追加参数个数。\n\n");

        output.Append("## 文档覆盖\n\n");
        output.Append("| 指标 | 数量 |\n| --- | --- |\n");
        output.Append("| 类型页 | ").Append(pages.Count).Append(" |\n");
        output.Append("| 　组件与引擎对象 | ").Append(pages.Count(page => page.Category == DocPages.Components)).Append(" |\n");
        output.Append("| 　值类型与枚举 | ").Append(pages.Count(page => page.Category == DocPages.Values)).Append(" |\n");
        output.Append("| 　托管层 | ").Append(pages.Count(page => page.Category == DocPages.Managed)).Append(" |\n");
        output.Append("| 成员条目 | ").Append(counts.Members).Append(" |\n");
        output.Append("| 　有注释 | ").Append(counts.Documented).Append(" |\n");
        output.Append("| 　　（注释取自编译器 xml） | ").Append(counts.XmlDocumented).Append(" |\n");
        output.Append("| 　　（注释取自 C++ 头文件投影） | ").Append(counts.ProjectionDocumented).Append(" |\n");
        output.Append("| 　没有注释 | ").Append(counts.Members - counts.Documented).Append(" |\n\n");
        output.Append("输入侧的对照：投影 ").Append(projection.Types.Count).Append(" 个对象类型、").Append(projection.Values.Count).Append(" 个值类型、");
        output.Append(projection.Types.Sum(type => type.Members.Count)).Append(" 个成员，其中 ").Append(projection.Types.Sum(type => type.Members.Count(member => member.Doc.Length != 0))).Append(" 个带头文件注释；");
        output.Append("编译器注释 ").Append(counts.Coverage.XmlEntries).Append(" 条，配对到反射成员 ").Append(counts.Coverage.XmlMatched).Append(" 条。\n\n");

        foreach (var category in CategoryOrder)
        {
            output.Append("## ").Append(CategoryTitle(category)).Append("\n\n");
            output.Append("| 类型 | 种类 | 说明 |\n| --- | --- | --- |\n");
            foreach (var page in pages.Where(page => page.Category == category).OrderBy(page => page.Name, StringComparer.Ordinal))
                output.Append("| [").Append(page.Name).Append("](").Append(DocPages.RelativePath(page)).Append(") | ").Append(page.Kind).Append(" | ").Append(Cell(page.Summary)).Append(" |\n");
            output.Append('\n');
        }
        return output.ToString();
    }

    /// <summary>从当前页所在目录指向目标页的相对链接。</summary>
    internal static string RelativeLink(string fromCategory, string targetRelativePath)
    {
        var target = targetRelativePath.Replace('\\', '/');
        return fromCategory.Length == 0 || target.StartsWith(fromCategory + "/", StringComparison.Ordinal) ? target[(fromCategory.Length + 1)..] : "../" + target;
    }

    /// <summary>索引里的分类顺序：先看游戏侧最常用的引擎对象，再看值类型，最后是托管层。</summary>
    private static readonly string[] CategoryOrder = [DocPages.Components, DocPages.Values, DocPages.Managed];

    private static string CategoryTitle(string category) => category switch
    {
        DocPages.Components => "组件与引擎对象",
        DocPages.Values => "值类型与枚举",
        _ => "托管层"
    };

    //序列化与变更回调决定字段在 Inspector 里的行为，单独点出来
    private static string EditorFlags(DocEntry entry)
    {
        List<string> flags = [];
        if (entry.Serialized) flags.Add("序列化字段");
        if (entry.Changed.Length != 0) flags.Add("变更回调 `" + entry.Changed + "()`");
        return string.Join("　·　", flags);
    }

    //竖线会截断表格单元格
    private static string Cell(string text) => Escape(text).Replace("|", "\\|");

    private static string Escape(string text) => text.Replace("\r", "").Replace("\n", " ").Trim();

    private static string ShortName(string fullName)
    {
        var index = fullName.LastIndexOf('.');
        return index < 0 ? fullName : fullName[(index + 1)..];
    }
}

/// <summary>统计口径：页面数、成员数与注释来源分布。</summary>
internal sealed class ManifestCounts
{
    public int Members { get; set; }
    public int Documented { get; set; }
    public int XmlDocumented { get; set; }
    public int ProjectionDocumented { get; set; }
    public XmlCoverage Coverage { get; set; } = new();
}
