<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>OrbedenDocGen</AssemblyName>
    <RootNamespace>OrbedenDocGen</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../OrbedenCore/Managed/OrbedenCore.CSharp/Interop/InteropText.cs" Link="Interop/InteropText.cs" />
  </ItemGroup>
</Project>
